#cloud-config

package_update: true
package_upgrade: true

write_files:
- path: /etc/sudoers.d/99-centos-cloud-init-requiretty
  permissions: 440
  content: |
    Defaults:centos !requiretty
- path: /etc/aws/aws.conf
  permissions: 644
  content: |
    [Global]
    Zone = ${aws_region}

packages:
- bind-utils
- telnet
- vim
- epel-release
- git
- docker

runcmd:
- yum install -y python-pip jq
- pip install --upgrade pip awscli
- curl -fsSL "${openshift_url}" | tar -xzf - -C /usr/local/bin --strip-components 1
- >
  echo '{
    "Comment": "auto updated @ '$(date)'",
    "Changes": [{
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "'$(curl -Lfs http://169.254.169.254/latest/meta-data/local-hostname)'",
        "Type": "A",
        "TTL": 60,
        "ResourceRecords": [{
          "Value": "'$(curl -Lfs http://169.254.169.254/latest/meta-data/local-ipv4)'"
        }]
      }
    }]
  }' > /tmp/route53_update.json &&
  aws route53 change-resource-record-sets --hosted-zone-id ${dns_zone_id} --change-batch file:///tmp/route53_update.json

power_state:
  delay: "+30"
  mode: poweroff
  message: Bootstrap failed, terminating instance.
  timeout: 30
  condition: 1

power_state:
  delay: "+10"
  mode: reboot
  message: Bootstrap success, reboot instance.
  timeout: 30
  condition: 0
