#cloud-config

package_update: true
package_upgrade: true

write_files:
- path: /etc/sudoers.d/99-centos-cloud-init-requiretty
  permissions: 440
  content: |
    Defaults:centos !requiretty
- path: /etc/aws/aws.conf
  permissions: 644
  content: |
    [Global]
    Zone = ${aws_region}

packages:
- bind-utils
- telnet
- vim
- epel-release
- git
- docker
- NetworkManager

runcmd:
- yum install -y python-pip jq
- pip install --upgrade pip awscli
- curl -fsSL "${openshift_url}" | tar -xzf - -C /usr/local/bin --strip-components 1
- >
  echo '{
    "Comment": "auto updated @ '$(date)'",
    "Changes": [{
      "Action": "UPSERT",
      "ResourceRecordSet": {
        "Name": "'$(curl -Lfs http://169.254.169.254/latest/meta-data/local-hostname)'",
        "Type": "A",
        "TTL": 60,
        "ResourceRecords": [{
          "Value": "'$(curl -Lfs http://169.254.169.254/latest/meta-data/local-ipv4)'"
        }]
      }
    }]
  }' > /tmp/route53_update.json &&
  aws route53 change-resource-record-sets --hosted-zone-id ${dns_zone_id} --change-batch file:///tmp/route53_update.json
- systemctl enable NetworkManager
- systemctl start NetworkManager
- export AWS_DEFAULT_REGION=$(curl -Lfs http://169.254.169.254/latest/dynamic/instance-identity/document|grep region|awk -F\" '{print $4}')
- AWS_AZ=$(curl -Lfs http://169.254.169.254/latest/meta-data/placement/availability-zone)
- INSTANCE_ID=$(curl -Lfs http://169.254.169.254/latest/meta-data/instance-id)
- NFS_EBS_VOLUME=$(aws ec2 describe-volumes --filters Name=availability-zone,Values=$AWS_AZ,Name=status,Values=available,Name=tag:clusterid,Values=${cluster_id},Name=tag:environment,Values=${cluster_env},Name=tag:host-type,Values=nfs | jq -r '.Volumes[].VolumeId')
- [ $(grep -c -E vol-[0-9a-z]\{17\} <<< $NFS_EBS_VOLUME) = 1 ] && aws ec2 attach-volume --instance-id $INSTANCE_ID --volume-id $NFS_EBS_VOLUME --device /dev/xvdx
- mkdir -p /exports
- mount /dev/xvdx /exports

power_state:
  delay: "+30"
  mode: poweroff
  message: Bootstrap failed, terminating instance.
  timeout: 30
  condition: 1

power_state:
  delay: "+10"
  mode: reboot
  message: Bootstrap success, reboot instance.
  timeout: 30
  condition: 0
